--- 
title: "Human Development Analysis"
author: "Zohaib Anwar, Lu Bin Liu, Michelle Strayer"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

The United Nations Development Programme releases yearly reports and extensive data on international human development indicators, which have been used to examine progress and setbacks in national development around the world. Human development data are versatile and extensive, allowing analysis of a variety of variables across time and region.  These datasets have been used in a wide variety of research, and continue to be used in international aid and development analyses, benchmarking, trend analysis in the fields of nutrition, gender, economic and social progress, and much more. As an example, see [this paper](https://www.jstor.org/stable/43859903?seq=1).

This study investigates the relationships between selected Human Security, Inequality, and Education variables to identify associations between individual variables and isolate trends among country clusters. As the breadth of the human development datasets is extensive, this study does not present a deep dive into any one country or region, though regional analysis is suggested as a dimension of further research. Rather, this study provides an overview of the trends and associations between selected variables, draws observational conclusions regarding their relationships, and uses these analyses to suggest directions for further research.